name: uplink
version: 0.1.0
synopsis: A distributed ledger for finance.
maintainer: Stephen Diehl (stephen@adjoint.io)
license: Apache
github: adjoint-io/uplink
category: Database
extra-source-files:
  - README.md


flags:
  static:
    description: Emit statically-linked binary
    manual: False
    default: False

  optimized:
    description: Perform compiler optimizations
    manual: False
    default: False

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - deepseq
  - directory
  - filepath
  - network
  - unix
  - process
  - array
  - pretty-show
  - safe
  - hslogger
  - gitrev
  - scientific
  - filelock
  - ansi-terminal

  # Date & Time
  - time
  - datetimes
  - hourglass

  # Control Structures
  - mtl >= 2.2
  - transformers-base

  # Data Structures
  - containers
  - hashable ==1.2.4.0
  - unordered-containers
  - fgl
  - dlist
  - merkle-tree

  # Exceptions
  - exceptions

  # Concurrency
  - stm
  - async

  # Text
  - text
  - bytestring
  - parsec
  - wl-pprint-text
  - base58-bytestring
  - base64-bytestring

  # Cryptograhy
  - cryptonite >= 0.21
  - memory
  - pem
  - x509
  - asn1-types
  - asn1-encoding
  - merkle-tree 
  - pedersen-commitment

  # Number Theory
  - arithmoi

  # Serialization
  - cereal
  - binary
  - configurator
  - aeson >= 0.11
  - aeson-pretty
  - pretty-hex
  - hexpat >= 0.20
  - hexpat-pickle >= 0.6
 
  # Networking
  - http-types
  - http-client
  - network-transport
  - network-transport-tcp
  - network-transport-inmemory
  - distributed-process
  - wai-logger
  - warp
  - warp-tls

  # Persistence
  - leveldb-haskell

  # Console
  - repline
  - haskeline

  # Rpc server
  - scotty
  - lifted-base

  # Testing
  - random 

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-uni-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fwarn-hi-shadowing
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
    - FlexibleContexts
    - Rank2Types 

  when:
    - condition: os(linux) && flag(static)
      ghc-options: -static -optl-static

  exposed-modules:
    # Application
    - Driver
    - Config
    - Opts
    - Account 
    - Logging
    - Utils
    - Version
    
    # Console
    - Console
    - Console.Config
    - Console.Command
    - Console.Completion
    - Console.Parser
    - Console.Lexer

    # Ledger
    - Ledger
    - Block
    - Asset
    - Contract
    - Bind
    - Transaction
    - Storage
    - MemPool
    - Time

    # Addresses
    - Address
    - Derivation

    # Cryptography
    - Hash
    - Key
    - Homomorphic
    - Shamir
    - Threshold
    - Commit
    - Encoding

    # Database
    - DB
    - TxLog
    - XML

    # Networking
    - RPC
    - NodeState
    - SafeString
    - SafeInteger
    - Network.Utils
    - Network.P2P
    - Network.P2P.Cmd
    - Network.P2P.Controller
    - Network.P2P.Consensus
    - Network.P2P.Message
    - Network.P2P.Service 

    # Consensus
    - Consensus
    - Consensus.Authority
    - Consensus.Authority.Types
    - Authority

    # Validation
    - Validate
       
    # Contracts
    - Script
    - Delta
    - Script.Init
    - Script.Fixed
    - Script.Storage
    - Script.Pretty
    - Script.Graph
    - Script.Error
    - Script.Eval
    - Script.Prim
    - Script.Token
    - Script.Lexer
    - Script.Parser
    - Script.Compile
    - Script.Typecheck
    - Script.Analysis

executables:
  uplink:
    main: Main.hs
    source-dirs: exe
    default-extensions:
      - NoImplicitPrelude
      - OverloadedStrings
    other-modules:
      Paths_uplink
    when:
      - condition: os(linux) && flag(static)
        ghc-options: -static -optl-static
      - condition: flag(optimized)
        ghc-options: -threaded -O2 -rtsopts 
    dependencies:
      - uplink
      - protolude >= 0.2
      - optparse-applicative

tests:
  uplink-test:
    dependencies:
    - base >= 4.7 && < 5
    - uplink
    - protolude >= 0.2
    - aeson
    - cereal
    - QuickCheck
    - tasty
    - pretty-hex
    - tasty-golden
    - tasty-hunit
    - tasty-quickcheck
    main: Main.hs
    source-dirs: tests

benchmarks:
  uplink-benchmarks:
    source-dirs: bench
    main: Main.hs
    dependencies:
    - uplink 
    - criterion
